package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA



/**
 * ClusterSpace generated by hbm2java
 */
public class ClusterSpace  implements java.io.Serializable {


     private ClusterSpaceId id;

    public ClusterSpace() {
    }
    
    public ClusterSpace(ClusterSpaceId id) {
       this.id = id;
    }
   
    public ClusterSpaceId getId() {
        return this.id;
    }
    
    public void setId(ClusterSpaceId id) {
        this.id = id;
    }




}


