package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Link generated by hbm2java
 */
public class Link  implements java.io.Serializable {


     private int linkId;
     private String url;
     private Integer totalPosts;
     private String hash;
     private String title;
     private Set saveLinks = new HashSet(0);

    public Link() {
    }

	
    public Link(int linkId) {
        this.linkId = linkId;
    }
    public Link(int linkId, String url, Integer totalPosts, String hash, String title, Set saveLinks) {
       this.linkId = linkId;
       this.url = url;
       this.totalPosts = totalPosts;
       this.hash = hash;
       this.title = title;
       this.saveLinks = saveLinks;
    }
   
    public int getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(int linkId) {
        this.linkId = linkId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getTotalPosts() {
        return this.totalPosts;
    }
    
    public void setTotalPosts(Integer totalPosts) {
        this.totalPosts = totalPosts;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getSaveLinks() {
        return this.saveLinks;
    }
    
    public void setSaveLinks(Set saveLinks) {
        this.saveLinks = saveLinks;
    }




}


