package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SaveLink generated by hbm2java
 */
public class SaveLink  implements java.io.Serializable {


     private int saveLinkId;
     private Author author;
     private Link link;
     private Date dateSave;
     private String title;
     private String description;
     private Set tagLinks = new HashSet(0);

    public SaveLink() {
    }

	
    public SaveLink(int saveLinkId) {
        this.saveLinkId = saveLinkId;
    }
    public SaveLink(int saveLinkId, Author author, Link link, Date dateSave, String title, String description, Set tagLinks) {
       this.saveLinkId = saveLinkId;
       this.author = author;
       this.link = link;
       this.dateSave = dateSave;
       this.title = title;
       this.description = description;
       this.tagLinks = tagLinks;
    }
   
    public int getSaveLinkId() {
        return this.saveLinkId;
    }
    
    public void setSaveLinkId(int saveLinkId) {
        this.saveLinkId = saveLinkId;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public Link getLink() {
        return this.link;
    }
    
    public void setLink(Link link) {
        this.link = link;
    }
    public Date getDateSave() {
        return this.dateSave;
    }
    
    public void setDateSave(Date dateSave) {
        this.dateSave = dateSave;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTagLinks() {
        return this.tagLinks;
    }
    
    public void setTagLinks(Set tagLinks) {
        this.tagLinks = tagLinks;
    }




}


