package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private int tagId;
     private String tagName;
     private Set tagLinks = new HashSet(0);

    public Tag() {
    }

	
    public Tag(int tagId) {
        this.tagId = tagId;
    }
    public Tag(int tagId, String tagName, Set tagLinks) {
       this.tagId = tagId;
       this.tagName = tagName;
       this.tagLinks = tagLinks;
    }
   
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    public Set getTagLinks() {
        return this.tagLinks;
    }
    
    public void setTagLinks(Set tagLinks) {
        this.tagLinks = tagLinks;
    }




}


