package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA



/**
 * ClusterSpaceId generated by hbm2java
 */
public class ClusterSpaceId  implements java.io.Serializable {


     private int link;
     private int clusterId;

    public ClusterSpaceId() {
    }

    public ClusterSpaceId(int link, int clusterId) {
       this.link = link;
       this.clusterId = clusterId;
    }
   
    public int getLink() {
        return this.link;
    }
    
    public void setLink(int link) {
        this.link = link;
    }
    public int getClusterId() {
        return this.clusterId;
    }
    
    public void setClusterId(int clusterId) {
        this.clusterId = clusterId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClusterSpaceId) ) return false;
		 ClusterSpaceId castOther = ( ClusterSpaceId ) other; 
         
		 return (this.getLink()==castOther.getLink())
 && (this.getClusterId()==castOther.getClusterId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLink();
         result = 37 * result + this.getClusterId();
         return result;
   }   


}


