package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA



/**
 * FollowingId generated by hbm2java
 */
public class FollowingId  implements java.io.Serializable {


     private int follower;
     private int followee;

    public FollowingId() {
    }

    public FollowingId(int follower, int followee) {
       this.follower = follower;
       this.followee = followee;
    }
   
    public int getFollower() {
        return this.follower;
    }
    
    public void setFollower(int follower) {
        this.follower = follower;
    }
    public int getFollowee() {
        return this.followee;
    }
    
    public void setFollowee(int followee) {
        this.followee = followee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FollowingId) ) return false;
		 FollowingId castOther = ( FollowingId ) other; 
         
		 return (this.getFollower()==castOther.getFollower())
 && (this.getFollowee()==castOther.getFollowee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFollower();
         result = 37 * result + this.getFollowee();
         return result;
   }   


}


