package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Following generated by hbm2java
 */
public class Following  implements java.io.Serializable {


     private FollowingId id;
     private Author authorByFollowee;
     private Author authorByFollower;
     private Date dateFollow;

    public Following() {
    }

	
    public Following(FollowingId id, Author authorByFollowee, Author authorByFollower) {
        this.id = id;
        this.authorByFollowee = authorByFollowee;
        this.authorByFollower = authorByFollower;
    }
    public Following(FollowingId id, Author authorByFollowee, Author authorByFollower, Date dateFollow) {
       this.id = id;
       this.authorByFollowee = authorByFollowee;
       this.authorByFollower = authorByFollower;
       this.dateFollow = dateFollow;
    }
   
    public FollowingId getId() {
        return this.id;
    }
    
    public void setId(FollowingId id) {
        this.id = id;
    }
    public Author getAuthorByFollowee() {
        return this.authorByFollowee;
    }
    
    public void setAuthorByFollowee(Author authorByFollowee) {
        this.authorByFollowee = authorByFollowee;
    }
    public Author getAuthorByFollower() {
        return this.authorByFollower;
    }
    
    public void setAuthorByFollower(Author authorByFollower) {
        this.authorByFollower = authorByFollower;
    }
    public Date getDateFollow() {
        return this.dateFollow;
    }
    
    public void setDateFollow(Date dateFollow) {
        this.dateFollow = dateFollow;
    }




}


