package model.pojo;
// Generated Dec 22, 2012 8:13:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TagCollect generated by hbm2java
 */
public class TagCollect  implements java.io.Serializable {


     private int id;
     private String tagName;
     private Date dateTagged;

    public TagCollect() {
    }

	
    public TagCollect(int id, String tagName) {
        this.id = id;
        this.tagName = tagName;
    }
    public TagCollect(int id, String tagName, Date dateTagged) {
       this.id = id;
       this.tagName = tagName;
       this.dateTagged = dateTagged;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    public Date getDateTagged() {
        return this.dateTagged;
    }
    
    public void setDateTagged(Date dateTagged) {
        this.dateTagged = dateTagged;
    }




}


