package model.pojo;
// Generated Oct 21, 2012 11:19:59 PM by Hibernate Tools 3.2.1.GA



/**
 * TagLinkId generated by hbm2java
 */
public class TagLinkId  implements java.io.Serializable {


     private int saveLinkId;
     private int tagId;

    public TagLinkId() {
    }

    public TagLinkId(int saveLinkId, int tagId) {
       this.saveLinkId = saveLinkId;
       this.tagId = tagId;
    }
   
    public int getSaveLinkId() {
        return this.saveLinkId;
    }
    
    public void setSaveLinkId(int saveLinkId) {
        this.saveLinkId = saveLinkId;
    }
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TagLinkId) ) return false;
		 TagLinkId castOther = ( TagLinkId ) other; 
         
		 return (this.getSaveLinkId()==castOther.getSaveLinkId())
 && (this.getTagId()==castOther.getTagId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSaveLinkId();
         result = 37 * result + this.getTagId();
         return result;
   }   


}


